#!/usr/bin/python3
from sys import argv
import math

def is_prime(num):
    """Check if a number is prime."""
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def find_factors(n):
    """Find two prime factors of n."""
    if n % 2 == 0:
        return 2, n // 2  # Special case for even numbers
    
    # Check for odd factors
    for i in range(3, int(math.sqrt(n)) + 1, 2):
        if n % i == 0:
            factor = n // i
            if is_prime(i) and is_prime(factor):
                return i, factor
    return None

def main():
    if len(argv) < 2:
        print("Usage: python3 script.py <filename>")
        return
    
    with open(argv[1]) as f:
        for line in f:
            num = int(line.strip())  # Strip any whitespace/newlines
            print("{:d} = ".format(num), end='')
            factors = find_factors(num)
            if factors:
                print("{} * {}".format(factors[0], factors[1]))
            else:
                print("No prime factors found.")

if __name__ == "__main__":
    main()
